sudo: true
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - sudo apt-get install xvfb libreoffice libfile-mimeinfo-perl inkscape poppler-utils libimage-exiftool-perl -y
  - pip install xvfbwrapper
  - python setup.py install
  - pip install pytest
  - python3 -m pip install -U mypy

# command to run tests
script:
  - "cd ${TRAVIS_BUILD_DIR} && py.test tests"

#  - "cd ${TRAVIS_BUILD_DIR} && mypy preview_generator --ignore-missing-imports --disallow-untyped-defs"


                              
